### ISSUE TITLE
 js_native_api.h not found on pretest build

### ISSUE THREAD

**Issue by cerisano** [nodejs/webidl-napi#4]
When running npm run pretest get the following errors. Possibly a dependency is missing?
Tried adding `node-addon-api` to package.json, same result.

```
dcerisano@kronos:~/git/webgpu-napi/webidl-napi$ npm run pretest

> webidl-napi@0.0.0 pretest /home/dcerisano/git/webgpu-napi/webidl-napi
> node test/build.js

make: Entering directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu/build'
  RULE binding_gyp_webgpu_target_idl2cc_0 webgpu.cc
  CXX(target) Release/obj.target/webgpu/webgpu.o
  CXX(target) Release/obj.target/webgpu/init.o
  CXX(target) Release/obj.target/webgpu/webgpu-impl.o
../webgpu.cc:1:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
webgpu.target.mk:126: recipe for target 'Release/obj.target/webgpu/webgpu.o' failed
make: *** [Release/obj.target/webgpu/webgpu.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../webgpu-impl.h:4:0,
                 from ../webgpu-impl.cc:2:
/home/dcerisano/git/webgpu-napi/webidl-napi/webidl-napi-inl.h:7:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
webgpu.target.mk:126: recipe for target 'Release/obj.target/webgpu/webgpu-impl.o' failed
make: *** [Release/obj.target/webgpu/webgpu-impl.o] Error 1
make: Leaving directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command "/home/dcerisano/.nvm/versions/node/v10.20.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
make: Entering directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example/build'
  RULE binding_gyp_example_target_idl2cc_0 example.cc
  CXX(target) Release/obj.target/example/example.o
  CXX(target) Release/obj.target/example/init.o
  CXX(target) Release/obj.target/example/example-impl.o
../example.cc:1:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
example.target.mk:126: recipe for target 'Release/obj.target/example/example.o' failed
make: *** [Release/obj.target/example/example.o] Error 1
make: *** Waiting for unfinished jobs....
../example-impl.cc:2:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
example.target.mk:126: recipe for target 'Release/obj.target/example/example-impl.o' failed
make: *** [Release/obj.target/example/example-impl.o] Error 1
make: Leaving directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command "/home/dcerisano/.nvm/versions/node/v10.20.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

**Comment by gabrielschulhof** [comment]
This is strange. How did you install Node.js?

**Comment by cerisano** [comment]
I use nvm to install node.
Which version of node is recommended for webidl-napi?

**Comment by gabrielschulhof** [comment]
@cerisano I guess you'd need Node.js >= 12.0.0. In 10.20.1 the separation between node_api.h and js_native_api.h had not yet taken place. I suppose I could add a detection to the build script.

**Comment by cerisano** [comment]
Confirm that nim req for webidl-napi is node 12
